// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH1B7ywNVcUK4n_fimElG9KVx7T1zsF2I',
    appId: '1:809738335591:web:c0b16d7550f5b01ab7ebc2',
    messagingSenderId: '809738335591',
    projectId: 'eventlift-42538',
    authDomain: 'eventlift-42538.firebaseapp.com',
    storageBucket: 'eventlift-42538.firebasestorage.app',
    measurementId: 'G-WKDDX9ET7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHJIrABSZyk41-1QaPeDq06H2udQ-7QmA',
    appId: '1:809738335591:android:a50d3493c7d9c6bdb7ebc2',
    messagingSenderId: '809738335591',
    projectId: 'eventlift-42538',
    storageBucket: 'eventlift-42538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6v5ikOndRlWDnD2_1eTWIdWjV2EDukFE',
    appId: '1:809738335591:ios:15118b4c1e541c67b7ebc2',
    messagingSenderId: '809738335591',
    projectId: 'eventlift-42538',
    storageBucket: 'eventlift-42538.firebasestorage.app',
    iosBundleId: 'com.example.eventlift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6v5ikOndRlWDnD2_1eTWIdWjV2EDukFE',
    appId: '1:809738335591:ios:15118b4c1e541c67b7ebc2',
    messagingSenderId: '809738335591',
    projectId: 'eventlift-42538',
    storageBucket: 'eventlift-42538.firebasestorage.app',
    iosBundleId: 'com.example.eventlift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH1B7ywNVcUK4n_fimElG9KVx7T1zsF2I',
    appId: '1:809738335591:web:22f6c09852e66486b7ebc2',
    messagingSenderId: '809738335591',
    projectId: 'eventlift-42538',
    authDomain: 'eventlift-42538.firebaseapp.com',
    storageBucket: 'eventlift-42538.firebasestorage.app',
    measurementId: 'G-HV8T6P6PW5',
  );
}
